Add User CRUD with Api Model
Leaf-Out/BackEnd pull request #10
Opened 2020-03-19 23:57 UTC by Sergyo97

2020-03-20 00:55 UTC, Alejoguzm07 requested changes

2020-03-20 00:55 UTC, Alejoguzm07 commented on src/main/java/leafout/backend/apimodel/UserRequest.java
> +    private String name;
Javadoc

2020-03-20 00:55 UTC, Alejoguzm07 commented on src/main/java/leafout/backend/apimodel/UserResponse.java
> +    private String name;
Javadoc

2020-03-20 00:55 UTC, Alejoguzm07 commented on src/main/java/leafout/backend/controller/UserController.java
> +@RequestMapping(value = "/users")
Javadoc

2020-03-20 00:55 UTC, Alejoguzm07 commented on src/main/java/leafout/backend/controller/UserController.java
> +    public ResponseEntity<?> getAll(){
Explicit return type

2020-03-20 00:55 UTC, Alejoguzm07 commented on src/main/java/leafout/backend/controller/UserController.java
> +            List<User> users =  userService.getAll();
final modifier

2020-03-20 00:55 UTC, Alejoguzm07 commented on src/main/java/leafout/backend/controller/UserController.java
> +        }catch (Exception e){
Explicit exception type

2020-03-20 00:55 UTC, Alejoguzm07 commented on src/main/java/leafout/backend/service/IUserService.java
> +    List<User> getAll();
Javadoc to be implemented by the impl

2020-03-25 03:39 UTC, Alejoguzm07 approved these changes

2020-03-25 05:31 UTC, QSARJP approved these changes

2020-03-26 02:51 UTC, merged